### ISSUE TITLE
yarn link laravel-factory faild, shoud it be 'yarn link laravel-file-factory'?

### ISSUE THREAD

**Issue by smartymoon** [pipe-dream/docs#2]

**Comment by ajthinking** [comment]
Hey XinBa nice to see you here!! 😄
You are totally right, good spotting. Would you like to PR a fix to that and become a official contributor? Its good to test if these instructions work and are understandable to newcomers. Very appreciated, thanks!

**Comment by ajthinking** [comment]
Fixed by #3 😃

**Comment by smartymoon** [comment]
I am really excited for receiving your invest. 
It's great chance to me and I am glad to contribute my code. 😄

**Comment by ajthinking** [comment]
Cool! Just need your email to send invite :)

**Comment by smartymoon** [comment]
pp787qq@gmail.com  @ajthinking
