### ISSUE TITLE
yarn link syntax

### ISSUE THREAD

**Issue by CPSibo** [pipe-dream/docs#4]
Forgive me if this is something dumb since I've not used yarn before. After doing `yarn link`, the yarn CLI says to use the links with
```
yarn link "@pipe-dream/core"
yarn link "@pipe-dream/laravel-file-factory"
```
Using the syntax in your README always failed and I didn't see anything online that says why it wants it one way or the other. Even yarn's own online documentation has it using your simpler syntax (eg `yarn link laravel-file-factory`).

**Comment by ajthinking** [comment]
Hi CPSibo, thanks for spotting this issue!
I just fixed some outdated instructions in the readme. The name refers to the `name` key in the linked packages `package.json` file. In the case of the pipe dream repos they are all prefixed with `@pipe-dream/`. Does that solve your problem?

**Comment by ajthinking** [comment]
Also updated build instrutions

| repo  | build |
| ------------- | ------------- |
| `core`  | `yarn build --watch`  |
| `laravel-file-factory`  | `yarn watch`  |
| `laravel-create`  | `yarn watch`  |

**Comment by CPSibo** [comment]
Thank you for explaining it. The docs now match what I had to enter to get it working.
